apiVersion: v1
kind: ServiceAccount
metadata:
  name: lanchonete-app-sa
  namespace: app
  labels:
    project: good-burger
    env: dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::822619186337:role/gb-dev-eks-app-secrets