apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete-db
  template:
    metadata:
      labels:
        app: lanchonete-db
    spec:
      containers:
        - name: lanchonete-db
          image: efabio/lanchonete-db:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc