apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::822619186337:role/gb-dev-eks-node-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::822619186337:role/gb-dev-gha-lanchonete-app
      username: gha
      groups:
        - system:masters
  mapUsers: |
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
