name: oidc-smoke
on: [workflow_dispatch]
permissions:
  id-token: write
  contents: read
jobs:
  whoami:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TERRAFORM }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: STS GetCallerIdentity
        run: aws sts get-caller-identity
